name: Terraform

on:
  push:
    branches:
      - feature
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: enviorment/Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false -backend-config="storage_account_name=teststorage087" -backend-config="container_name=test-scenerio" -backend-config="key=prod.terraform.tfstate" -backend-config="use_azuread_auth=true"

      - name: Terraform Plan
        run: terraform plan -input=false -no-color

  apply:
    name: Terraform Apply
    needs: plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: enviorment/Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: eb49ab4d-0b62-4aeb-9816-635402c9f909
          tenant-id: 468c391b-b59b-498c-8676-0b015e2ac28c
          subscription-id: f8bb19d2-fa1c-44e1-b99d-f92784561646

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false -backend-config="storage_account_name=teststorage087" -backend-config="container_name=test-scenerio" -backend-config="key=prod.terraform.tfstate" -backend-config="use_azuread_auth=true"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
